name: Parties
version: 1.3.3
main: me.crazybanana.parties.Parties
api-version: 1.16
authors: [CrazyBanana]
description: Have parties in minecraft!
commands:
  party:
    description: This is a test!
    aliases: [p]